name: goreleaser

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-22.04-htzhel1-ax42-a
    steps:
      - name: Checkout
        uses: https://gitea.obmondo.com/Obmondo/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: https://gitea.obmondo.com/Obmondo/setup-go@v6.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run GoReleaser
        uses: https://gitea.obmondo.com/Obmondo/goreleaser-action@v6.4.0
        with:
          version: "v2.12.7"
          args: release --clean -f .goreleaser-gitea.yaml
        env:
          GITEA_TOKEN: ${{ secrets.GORELEASER_TOKEN }}

      - name: Upload to repo servers
        env:
          PUBLIC_PATH: /vol0/data/packagesign01_var/var/lib/packagesign/repos/incoming/public/
          USERNAME: ${{ secrets.PACKAGESIGN_USER }}
          SSH_KEY: ${{ secrets.PACKAGESIGN_SSH_KEY }}
          HOST: ${{ secrets.PACKAGESIGN_HOST }}
        run: |
          apt update && apt install -y rsync openssh-client
          echo "${SSH_KEY}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          eval $(ssh-agent)
          ssh-add /tmp/ssh_key
          echo "Uploading artifacts in dist/"
          ls -alh dist/
          rsync -azv dist/*.deb dist/*.rpm -e "ssh -o StrictHostKeyChecking=no" ${USERNAME}@${HOST}:${PUBLIC_PATH}
